# Generated by Django 3.2.11 on 2023-01-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_auto_20230130_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodwatchEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodwatch_id', models.IntegerField()),
                ('business_id', models.IntegerField(null=True)),
                ('name_of_establishment', models.CharField(max_length=100)),
                ('license_nr', models.IntegerField()),
                ('gtcc_foodwatch_id', models.IntegerField(null=True)),
                ('entity_class_id', models.IntegerField(null=True)),
                ('entity_class', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('po_box', models.IntegerField()),
                ('office_line', models.CharField(max_length=20)),
                ('office_email', models.EmailField(max_length=254)),
                ('makani_nr', models.IntegerField()),
                ('latitue_longitude', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category_id', models.IntegerField()),
                ('sub_category', models.CharField(max_length=100)),
                ('website_url', models.URLField(null=True)),
                ('office_mobile', models.CharField(max_length=20, null=True)),
                ('qr_code', models.TextField()),
                ('uae_region_id', models.IntegerField()),
                ('uae_region_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('fogwatch_sub_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fogwatch_sub_area', to='masters.subarea')),
                ('fogwatch_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fogwatch_sub_category', to='masters.subcategory')),
            ],
        ),
    ]
