# Generated by Django 3.2.11 on 2023-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwatch', '0003_alter_foodwatchentity_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwatchentity',
            name='business_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
