# Generated by Django 3.2.11 on 2023-01-31 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodwatch', '0005_alter_foodwatchentity_license_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodwatchentity',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foodwatch_entity_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
