# Generated by Django 3.2.11 on 2023-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwatch', '0006_foodwatchentity_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwatchentity',
            name='business_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='entity_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='foodwatch_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='latitue_longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='license_nr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='makani_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='office_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='office_line',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='po_box',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='qr_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='sub_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='sub_category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='uae_region_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='uae_region_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
