# Generated by Django 3.2.11 on 2023-01-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20230130_1633'),
        ('foodwatch', '0007_auto_20230131_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodwatchentity',
            name='fogwatch_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fogwatch_area', to='masters.area'),
        ),
        migrations.AddField(
            model_name='foodwatchentity',
            name='fogwatch_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fogwatch_category', to='masters.maincategory'),
        ),
        migrations.AddField(
            model_name='foodwatchentity',
            name='fogwatch_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fogwatch_zone', to='masters.zone'),
        ),
    ]
