# Generated by Django 3.2.11 on 2023-01-31 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodwatch', '0008_auto_20230131_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodwatchentity',
            name='active_contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fogwatch_active_contact_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodwatchentity',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Converted', 'Converted'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
    ]
