# Generated by Django 3.2.11 on 2023-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwatch', '0010_auto_20230131_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(null=True)),
                ('response', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10)),
            ],
        ),
    ]
