# Generated by Django 3.2.11 on 2023-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwatch', '0011_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='api_class',
            field=models.CharField(default='ENTITY_INFO', max_length=100),
            preserve_default=False,
        ),
    ]
