# Generated by Django 3.2.11 on 2023-01-24 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('gtcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_tag', inverse_match=True)], verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('emp_id', models.CharField(max_length=50, null=True)),
                ('link_id', models.IntegerField(null=True)),
                ('link_class', models.CharField(max_length=50, null=True)),
                ('license_no', models.CharField(max_length=50, null=True)),
                ('extension_number', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('emirate', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.content_file_name)),
                ('retrieve_password_otp', models.IntegerField(blank=True, null=True)),
                ('retrieve_password_otp_expired', models.BooleanField(default=True)),
                ('inviting_key', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_key', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('invited_date', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('invite_expiry_date', models.DateTimeField(null=True, verbose_name='created')),
                ('is_staff', models.BooleanField(default=False)),
                ('user_status', models.CharField(choices=[('Invited', 'Invited'), ('Activated', 'Activated'), ('Deactivated', 'Deactivated'), ('Deleted', 'Deleted')], default='Invited', max_length=100)),
                ('user_class', models.CharField(choices=[('Envirol', 'Envirol'), ('GTCC', 'GTCC'), ('Entity', 'Entity'), ('Foodwatch', 'Foodwatch')], max_length=10)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Driver', 'Driver'), ('Inspector', 'Inspector'), ('Operator', 'Operator')], max_length=10)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vehicle', to='gtcc.vehicledetail')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_designation', to='masters.designation')),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=100)),
                ('log_type', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout')], default='Login', max_length=100)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
