# Generated by Django 3.2.11 on 2023-01-24 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtcc', '0002_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_main_category', to='masters.maincategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area_area', to='masters.area'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subarea',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_area_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subarea',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_area_zone', to='masters.zone'),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_vehicle', to='gtcc.vehicledetail'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeofpayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_of_payment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeofpayment',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_of_payment_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='greasetrap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grease_trap_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='greasetrap',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grease_trap_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gate',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixture',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixture',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_zone', to='masters.zone'),
        ),
    ]
