# Generated by Django 3.2.11 on 2023-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='foodwatch_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subarea',
            name='foodwatch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='foodwatch_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='foodwatch_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
