# Generated by Django 3.2.11 on 2023-02-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20230130_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greasetrap',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
