# Generated by Django 3.2.11 on 2023-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_greasetrap_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='foodwatch_sub_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='foodwatch_sub_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
