# Generated by Django 3.2.11 on 2023-02-20 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20230203_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='gate_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
