# Generated by Django 3.2.11 on 2023-02-20 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_gate_gate_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='gate_key',
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
