# Generated by Django 3.2.11 on 2023-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20230220_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.UUIDField(default='kCEOBzZDKRPKID4UHC1sYCUYnZWJui5I', editable=False),
        ),
    ]
