# Generated by Django 3.2.11 on 2023-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_gate_gate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='9x06UnMtibJ9fbQtaqcjMzngEAl8Fw9Y', editable=False, max_length=32, unique=True),
        ),
    ]
