# Generated by Django 3.2.11 on 2023-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20230220_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='Reb58NLlPN1Ajt1MBfOz4j1YATMpYxZb', editable=False, max_length=32, unique=True),
        ),
    ]
