# Generated by Django 3.2.11 on 2023-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_gate_gate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='9fDuRw1wgTZ8k8g14nnCj8UqcvK0AWfp', editable=False, max_length=32, unique=True),
        ),
    ]
