# Generated by Django 3.2.11 on 2023-02-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_gate_gate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='Kd0bKQcTtRwsfw0xySmXzmmsnyWzoOCe', editable=False, max_length=32, unique=True),
        ),
    ]
