# Generated by Django 3.2.11 on 2023-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_alter_gate_gate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='rfid_class',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Envirol', 'Envirol')], default='Truck', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='JMMG8eRQuRkY2LMiH5kYYSceSn8zjir4', editable=False, max_length=32, unique=True),
        ),
    ]
