# Generated by Django 3.2.11 on 2023-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_auto_20230224_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='tLmUDEr4LPeIalqdtqmRnR7s4q1a3iz4', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='friendly_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='tag_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
