# Generated by Django 3.2.11 on 2023-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_auto_20230224_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate',
            old_name='remote',
            new_name='remote_status',
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(default='3cPVHwIxQSOUMWg7XXNKsLZv1NEpOEOg', editable=False, max_length=32, unique=True),
        ),
    ]
