# Generated by Django 3.2.11 on 2023-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_auto_20230224_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
