# Generated by Django 3.2.11 on 2023-03-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_alter_gate_gate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='last_query_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RFIDTappingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_number', models.CharField(max_length=20)),
                ('tapped_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('vehicle_entry_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Failed', max_length=10)),
                ('tapped_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(null=True)),
                ('response', models.CharField(max_length=100, null=True)),
                ('gate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapped_gate', to='masters.gate')),
                ('rfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapped_rfid', to='masters.rfidcard')),
            ],
        ),
    ]
