fields = 'id, active_contact_person_id, active_gtcc_detail_id, area_id, category_id, entity_location, env_sap_id, establishment_name, foodwatch_business_id, location_remark, makhani_no, meals_per_day, phone_no, po_box, seating_capacity, status, sub_category_id, subarea_id, trade_license_name, trade_license_no, zone_id'
search_in_details = {
        'establishment_name' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'establishment_name',
            'fields': fields
        },
        'trade_license_no' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'trade_license_no',
            'fields': fields
        },
        'env_sap_id' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'env_sap_id',
            'fields': fields
        },
        'foodwatch_business_id' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'foodwatch_business_id',
            'fields': fields
        },
        'phone_no' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'phone_no',
            'fields': fields
        },
        'entity_location' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'entity_location',
            'fields': fields
        },
        'location_remark' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'location_remark',
            'fields': fields
        },
        'po_box' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'po_box',
            'fields': fields
        },
        'seating_capacity' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'seating_capacity',
            'fields': fields
        },
        'makhani_no' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'makhani_no',
            'fields': fields
        },
        'meals_per_day' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'meals_per_day',
            'fields': fields
        },
        'status' : {
            'table_name' : 'public.entity_entity',
            'cell_name' : 'status',
            'fields': fields
        },
    }

greaseTrapTypes = [
  {
    "grease_trap_id": "TP1",
    "foodwatch_id": "FDWTP1",
    "part_no": 1025668,
    "trap_label": "KESSELNS10",
    "capacity": 600,
    "material": "stainless steel",
    "shape": "Cuboid",
    "manufacturer": "ACO Building Drainage",
    "width": 6,
    "length": 6,
    "image": "grease_traps/trp1.jpeg",
    "remarks": "KESSELNS10Separator-500-600(2)"
  },
  {
    "grease_trap_id": "TP2",
    "foodwatch_id": "FDWTP2",
    "part_no": 1025669,
    "trap_label": "KESSELNS15",
    "capacity": 800,
    "material": "stainless steel",
    "shape": "Cube",
    "manufacturer": "Aluline",
    "width": 8,
    "length": 8,
    "image": "grease_traps/trp2.jpeg",
    "remarks": "KESSELNS15Separator-687-800(1)"
  },
  {
    "grease_trap_id": "TP3",
    "foodwatch_id": "FDWTP3",
    "part_no": 1025670,
    "trap_label": "SPT-100-5000(1)",
    "capacity": 5000,
    "material": "stainless steel",
    "shape": "Sphere",
    "manufacturer": "Asio",
    "width": 50,
    "length": 50,
    "image": "grease_traps/trp3.jpeg",
    "remarks": "SPT-100-5000(1)"
  },
  {
    "grease_trap_id": "TP4",
    "foodwatch_id": "FDWTP4",
    "part_no": 1025671,
    "trap_label": "SPT-100-5000(2)",
    "capacity": 5000,
    "material": "stainless steel",
    "shape": "Cylinder",
    "manufacturer": "BioMicrobics",
    "width": 50,
    "length": 50,
    "image": "grease_traps/trp4.jpeg",
    "remarks": "SPT-100-5000(2)"
  },
  {
    "grease_trap_id": "TP5",
    "foodwatch_id": "FDWTP5",
    "part_no": 1025672,
    "trap_label": "SPT-225-300(1)",
    "capacity": 300,
    "material": "stainless steel",
    "shape": "Cuboid",
    "manufacturer": "Eloy",
    "width": 3,
    "length": 3,
    "image": "grease_traps/trp5.jpeg",
    "remarks": "SPT-225-300(1)"
  },
  {
    "grease_trap_id": "TP6",
    "foodwatch_id": "FDWTP6",
    "part_no": 1025673,
    "trap_label": "TNK-1000-1200(1)",
    "capacity": 1200,
    "material": "stainless steel",
    "shape": "Cube",
    "manufacturer": "Elkuch",
    "width": 12,
    "length": 12,
    "image": "grease_traps/trp6.jpeg",
    "remarks": "TNK-1000-1200(1)"
  },
  {
    "grease_trap_id": "TP7",
    "foodwatch_id": "FDWTP7",
    "part_no": 1025674,
    "trap_label": "TNK-150-250(1)",
    "capacity": 250,
    "material": "stainless steel",
    "shape": "Sphere",
    "manufacturer": "Simop",
    "width": 2.5,
    "length": 2.5,
    "image": "grease_traps/trp7.jpeg",
    "remarks": "TNK-150-250(1)"
  },
  {
    "grease_trap_id": "TP8",
    "foodwatch_id": "FDWTP8",
    "part_no": 1025675,
    "trap_label": "TNK-180-250(1)",
    "capacity": 250,
    "material": "stainless steel",
    "shape": "Cylinder",
    "manufacturer": "Graf",
    "width": 2.5,
    "length": 2.5,
    "image": "grease_traps/trp8.jpeg",
    "remarks": "TNK-180-250(1)"
  },
  {
    "grease_trap_id": "TP9",
    "foodwatch_id": "FDWTP9",
    "part_no": 1025676,
    "trap_label": "TNK-200-300(1)",
    "capacity": 300,
    "material": "stainless steel",
    "shape": "Cuboid",
    "manufacturer": "Asio",
    "width": 3,
    "length": 3,
    "image": "grease_traps/trp9.jpeg",
    "remarks": "TNK-200-300(1)"
  },
  {
    "grease_trap_id": "TP10",
    "foodwatch_id": "FDWTP10",
    "part_no": 1025677,
    "trap_label": "TNK-225-250(2)",
    "capacity": 250,
    "material": "stainless steel",
    "shape": "Cube",
    "manufacturer": "BioMicrobics",
    "width": 2.5,
    "length": 2.5,
    "image": "grease_traps/trp10.jpeg",
    "remarks": "TNK-225-250(2)"
  },
  {
    "grease_trap_id": "TP11",
    "foodwatch_id": "FDWTP11",
    "part_no": 1025678,
    "trap_label": "TNK-250-350(1)",
    "capacity": 350,
    "material": "stainless steel",
    "shape": "Sphere",
    "manufacturer": "Eloy",
    "width": 3.5,
    "length": 3.5,
    "image": "grease_traps/trp11.jpeg",
    "remarks": "TNK-250-350(1)"
  },
  {
    "grease_trap_id": "TP12",
    "foodwatch_id": "FDWTP12",
    "part_no": 1025679,
    "trap_label": "TNK-300-400(0.5)",
    "capacity": 400,
    "material": "stainless steel",
    "shape": "Cylinder",
    "manufacturer": "Elkuch",
    "width": 4,
    "length": 4,
    "image": "grease_traps/trp12.jpeg",
    "remarks": "TNK-300-400(0.5)"
  },
  {
    "grease_trap_id": "TP13",
    "foodwatch_id": "FDWTP13",
    "part_no": 1025680,
    "trap_label": "TNK-300-400(1)",
    "capacity": 400,
    "material": "stainless steel",
    "shape": "Cuboid",
    "manufacturer": "Eloy",
    "width": 4,
    "length": 4,
    "image": "grease_traps/trp1.jpeg",
    "remarks": "TNK-300-400(1)"
  },
  {
    "grease_trap_id": "TP14",
    "foodwatch_id": "FDWTP14",
    "part_no": 1025681,
    "trap_label": "TNK-300-600(1)",
    "capacity": 600,
    "material": "stainless steel",
    "shape": "Cube",
    "manufacturer": "Elkuch",
    "width": 6,
    "length": 6,
    "image": "grease_traps/trp2.jpeg",
    "remarks": "TNK-300-600(1)"
  },
  {
    "grease_trap_id": "TP15",
    "foodwatch_id": "FDWTP15",
    "part_no": 1025682,
    "trap_label": "TNK-400-500(0.5)",
    "capacity": 500,
    "material": "stainless steel",
    "shape": "Sphere",
    "manufacturer": "Simop",
    "width": 5,
    "length": 5,
    "image": "grease_traps/trp3.jpeg",
    "remarks": "TNK-400-500(0.5)"
  },
  {
    "grease_trap_id": "TP16",
    "foodwatch_id": "FDWTP16",
    "part_no": 1025683,
    "trap_label": "TNK-500-700(0.5)",
    "capacity": 700,
    "material": "stainless steel",
    "shape": "Cylinder",
    "manufacturer": "Graf",
    "width": 7,
    "length": 7,
    "image": "grease_traps/trp4.jpeg",
    "remarks": "TNK-500-700(0.5)"
  },
  {
    "grease_trap_id": "TP17",
    "foodwatch_id": "FDWTP17",
    "part_no": 1025684,
    "trap_label": "TNK-500-700(1)",
    "capacity": 700,
    "material": "stainless steel",
    "shape": "Cuboid",
    "manufacturer": "BioMicrobics",
    "width": 7,
    "length": 7,
    "image": "grease_traps/trp5.jpeg",
    "remarks": "TNK-500-700(1)"
  },
  {
    "grease_trap_id": "TP18",
    "foodwatch_id": "FDWTP18",
    "part_no": 1025685,
    "trap_label": "TNK-500-700(2)",
    "capacity": 700,
    "material": "stainless steel",
    "shape": "Cube",
    "manufacturer": "Eloy",
    "width": 7,
    "length": 7,
    "image": "grease_traps/trp6.jpeg",
    "remarks": "TNK-500-700(2)"
  },
  {
    "grease_trap_id": "TP19",
    "foodwatch_id": "FDWTP19",
    "part_no": 1025686,
    "trap_label": "TNK-800-1500(0.5)",
    "capacity": 1500,
    "material": "stainless steel",
    "shape": "Sphere",
    "manufacturer": "Elkuch",
    "width": 15,
    "length": 15,
    "image": "grease_traps/trp7.jpeg",
    "remarks": "TNK-800-1500(0.5)"
  },
  {
    "grease_trap_id": "TP20",
    "foodwatch_id": "FDWTP20",
    "part_no": 1025687,
    "trap_label": "TNK-900-1000(1)",
    "capacity": 1000,
    "material": "stainless steel",
    "shape": "Cylinder",
    "manufacturer": "Simop",
    "width": 10,
    "length": 10,
    "image": "grease_traps/trp8.jpeg",
    "remarks": "TNK-900-1000(1)"
  },
  {
    "grease_trap_id": "TP21",
    "foodwatch_id": "FDWTP21",
    "part_no": 1025688,
    "trap_label": "A",
    "capacity": 55,
    "material": "plastic",
    "shape": "Cuboid",
    "manufacturer": "Graf",
    "width": 0.55,
    "length": 0.55,
    "image": "grease_traps/trp9.jpeg",
    "remarks": "TypeA-40-55(2)"
  },
  {
    "grease_trap_id": "TP22",
    "foodwatch_id": "FDWTP22",
    "part_no": 1025689,
    "trap_label": "AG1",
    "capacity": 20,
    "material": "plastic",
    "shape": "Cube",
    "manufacturer": "Asio",
    "width": 0.2,
    "length": 0.2,
    "image": "grease_traps/trp10.jpeg",
    "remarks": "TypeAG1-15-20(4)"
  },
  {
    "grease_trap_id": "TP23",
    "foodwatch_id": "FDWTP23",
    "part_no": 1025690,
    "trap_label": "AG2",
    "capacity": 30,
    "material": "plastic",
    "shape": "Sphere",
    "manufacturer": "BioMicrobics",
    "width": 0.3,
    "length": 0.3,
    "image": "grease_traps/trp11.jpeg",
    "remarks": "TypeAG2-25-30(2)"
  },
  {
    "grease_trap_id": "TP24",
    "foodwatch_id": "FDWTP24",
    "part_no": 1025691,
    "trap_label": "AG3",
    "capacity": 50,
    "material": "plastic",
    "shape": "Cylinder",
    "manufacturer": "Eloy",
    "width": 0.5,
    "length": 0.5,
    "image": "grease_traps/trp12.jpeg",
    "remarks": "TypeAG3-40-50(2)"
  },
  {
    "grease_trap_id": "TP25",
    "foodwatch_id": "FDWTP25",
    "part_no": 1025692,
    "trap_label": "AG5",
    "capacity": 300,
    "material": "stainless steel",
    "shape": "Cuboid",
    "manufacturer": "Elkuch",
    "width": 3,
    "length": 3,
    "image": "grease_traps/trp7.jpeg",
    "remarks": "TypeAG5-250-300(1)"
  },
  {
    "grease_trap_id": "TP26",
    "foodwatch_id": "FDWTP26",
    "part_no": 1025693,
    "trap_label": "B",
    "capacity": 125,
    "material": "stainless steel",
    "shape": "Cube",
    "manufacturer": "Eloy",
    "width": 1.25,
    "length": 1.25,
    "image": "grease_traps/trp8.jpeg",
    "remarks": "TypeB-100-125(2)"
  },
  {
    "grease_trap_id": "TP27",
    "foodwatch_id": "FDWTP27",
    "part_no": 1025694,
    "trap_label": "C",
    "capacity": 165,
    "material": "stainless steel",
    "shape": "Sphere",
    "manufacturer": "Elkuch",
    "width": 1.65,
    "length": 1.65,
    "image": "grease_traps/trp9.jpeg",
    "remarks": "TypeC-135-165(2)"
  },
  {
    "grease_trap_id": "TP28",
    "foodwatch_id": "FDWTP28",
    "part_no": 1025695,
    "trap_label": "D",
    "capacity": 25,
    "material": "plastic",
    "shape": "Cylinder",
    "manufacturer": "Eloy",
    "width": 0.25,
    "length": 0.25,
    "image": "grease_traps/trp10.jpeg",
    "remarks": "TypeD-15-25(4)"
  }
]