# Generated by Django 3.2.11 on 2023-01-24 08:50

import django.core.validators
from django.db import migrations, models
import gtcc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Entered', 'Entered'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Dumped', 'Dumped'), ('Exited', 'Exited')], max_length=10, null=True)),
                ('accessed_time', models.DateTimeField(auto_now_add=True)),
                ('accessed_direction', models.CharField(choices=[('Entry', 'Entry'), ('Exit', 'Exit')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet_no', models.CharField(max_length=100, unique=True)),
                ('coupon_start_no', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Issued', 'Issued'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payload', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type_of_payment', models.CharField(choices=[('Card', 'Card'), ('Bank', 'Bank')], max_length=10)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Success', 'Success'), ('Failed', 'Failed')], default='Initiated', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_no', models.PositiveIntegerField()),
                ('returned_on', models.DateTimeField(null=True)),
                ('collected_remark', models.TextField(null=True)),
                ('collection_violation', models.BooleanField(default=False)),
                ('total_gallons', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('converted_on', models.DateTimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to=gtcc.models.content_file_name)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Used', 'Used'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='Issued', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CouponBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_end_no', models.PositiveIntegerField()),
                ('total_coupons', models.PositiveIntegerField()),
                ('used_coupons', models.PositiveIntegerField(default=0)),
                ('collected_by', models.CharField(max_length=100, null=True)),
                ('collected_on', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('In Use', 'In Use'), ('Used', 'Used')], default='Issued', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EditCouponLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.TextField()),
                ('edited_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('trade_license_no', models.CharField(max_length=100, null=True)),
                ('trade_license_name', models.CharField(max_length=100, null=True)),
                ('env_sap_id', models.CharField(max_length=100, null=True)),
                ('credit_available', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('foodwatch_id', models.IntegerField(null=True)),
                ('foodwatch_business_id', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('location_remark', models.CharField(max_length=255, null=True)),
                ('po_box', models.CharField(max_length=50, null=True)),
                ('website_url', models.CharField(max_length=255, null=True)),
                ('office_email', models.EmailField(max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('txn_no', models.CharField(max_length=100)),
                ('reference_no', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending Approval', 'Pending Approval'), ('Canceled', 'Canceled')], default='Approved', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=100, unique=True)),
                ('chassis_no', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_tank_capacity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('random_key', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, null=True)),
                ('entry_time', models.DateTimeField(null=True)),
                ('exit_time', models.DateTimeField(null=True)),
                ('total_gallon_collected', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_dumping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_gallon_dumped', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('operator_acceptance', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('remarks', models.TextField(null=True)),
                ('current_status', models.CharField(choices=[('Entered', 'Entered'), ('Exited', 'Exited')], max_length=10)),
            ],
            options={
                'ordering': ('entry_time',),
            },
        ),
    ]
