# Generated by Django 3.2.11 on 2023-01-24 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
        ('gtcc', '0001_initial'),
        ('entity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentrydetails',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleentrydetails_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleentrydetails',
            name='gtcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleentrydetails_gtcc', to='gtcc.gtcc'),
        ),
        migrations.AddField(
            model_name='vehicleentrydetails',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleentrydetails_vehicle', to='gtcc.vehicledetail'),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='gtcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail_gtcc', to='gtcc.gtcc'),
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_checkout', to='gtcc.checkoutdetail'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='gtcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_gtcc', to='gtcc.gtcc'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='mode_of_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_mode_of_payment', to='masters.modeofpayment'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gtcc',
            name='active_contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_contact_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gtcc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtcc_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gtcc',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtcc_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editcouponlog',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_coupon', to='gtcc.coupon'),
        ),
        migrations.AddField(
            model_name='editcouponlog',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponbooklet',
            name='booklet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gtcc.booklet'),
        ),
        migrations.AddField(
            model_name='couponbooklet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponbooklet',
            name='gtcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_assigned_gtcc', to='gtcc.gtcc'),
        ),
        migrations.AddField(
            model_name='couponbooklet',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklet_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponbooklet',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklet_assigned_vehicle', to='gtcc.vehicledetail'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='booklet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_booklet', to='gtcc.couponbooklet'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_collected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='converted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_converted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='dumping_vehicledetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_dumped_vehicledetails', to='gtcc.vehicleentrydetails'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='returned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_service_request', to='entity.servicerequest'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_vehicledetail', to='gtcc.vehicledetail'),
        ),
        migrations.AddField(
            model_name='checkoutdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkoutdetail',
            name='gtcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_gtcc', to='gtcc.gtcc'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booklet',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklet_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscontrollog',
            name='accessed_gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_vehicledetail', to='masters.gate'),
        ),
        migrations.AddField(
            model_name='accesscontrollog',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesscontrollog_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscontrollog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesscontrollog_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscontrollog',
            name='rfid_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesscontrollog_rfid', to='masters.rfidcard'),
        ),
        migrations.AddField(
            model_name='accesscontrollog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesscontrollog_vehicledetail', to='gtcc.vehicledetail'),
        ),
    ]
