# Generated by Django 3.2.11 on 2023-02-15 12:55

from django.db import migrations, models
import gtcc.models


class Migration(migrations.Migration):

    dependencies = [
        ('gtcc', '0004_auto_20230215_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtcc',
            name='image',
            field=models.ImageField(null=True, upload_to=gtcc.models.content_file_name),
        ),
    ]
