# Generated by Django 3.2.11 on 2023-03-03 08:44

from django.db import migrations, models
import gtcc.models


class Migration(migrations.Migration):

    dependencies = [
        ('gtcc', '0024_auto_20230303_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtcc',
            name='image',
            field=models.ImageField(null=True, upload_to=gtcc.models.content_file_name),
        ),
    ]
