# Generated by Django 3.2.11 on 2023-03-03 11:50

from django.db import migrations, models
import django.db.models.deletion
import gtcc.models


class Migration(migrations.Migration):

    dependencies = [
        ('gtcc', '0025_alter_gtcc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtcc',
            name='image',
            field=models.ImageField(null=True, upload_to=gtcc.models.content_file_name),
        ),
        migrations.CreateModel(
            name='DeliveryOrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_content', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle_entry_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_vehicle_entry_details', to='gtcc.vehicleentrydetails')),
            ],
        ),
    ]
