# Generated by Django 3.2.11 on 2023-03-07 12:04

from django.db import migrations, models
import gtcc.models


class Migration(migrations.Migration):

    dependencies = [
        ('gtcc', '0026_auto_20230303_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderreport',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gtcc',
            name='image',
            field=models.ImageField(null=True, upload_to=gtcc.models.content_file_name),
        ),
    ]
