# Generated by Django 3.2.11 on 2023-03-07 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gtcc.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtcc', '0027_auto_20230307_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderreport',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='do_created_by', to='users.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorderreport',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryorderreport',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gtcc',
            name='image',
            field=models.ImageField(null=True, upload_to=gtcc.models.content_file_name),
        ),
    ]
