# Generated by Django 3.2.11 on 2023-01-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='discharge_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Assigned', 'Assigned'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Discharged', 'Discharged'), ('Canceled', 'Canceled')], default='Initiated', max_length=20),
        ),
    ]
