# Generated by Django 3.2.11 on 2023-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20230125_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='cleaning_status',
            field=models.CharField(choices=[('Cleaned', 'Cleaned'), ('Due', 'Due'), ('Overdue', 'Overdue')], default='Cleaned', max_length=10),
        ),
        migrations.AddField(
            model_name='entity',
            name='inspection_status',
            field=models.CharField(choices=[('Inspected', 'Inspected'), ('Due', 'Due'), ('Overdue', 'Overdue')], default='Inspected', max_length=10),
        ),
    ]
